"""Initial migration

Revision ID: 7e349de4489d
Revises: 
Create Date: 2026-06-18 16:12:38.985362

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '7e349de4489d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('audit_logs_2026_06')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('operation', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('record_pk', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('changed_at', 'id', name=op.f('audit_logs_2026_06_pkey'))
    pass
    # ### end Alembic commands ###
