"""add_shift_to_loco_bookings

Revision ID: 8dcfb4bbf5e9
Revises: c29ca691d8a5
Create Date: 2026-06-18 22:56:42.443968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dcfb4bbf5e9'
down_revision: Union[str, Sequence[str], None] = 'c29ca691d8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_table('audit_logs_2026_06')
    op.add_column('loco_bookings', sa.Column('shift', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loco_bookings', 'shift')
    op.create_table('audit_logs_2026_06',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('record_pk', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('changed_at', 'id', name=op.f('audit_logs_2026_06_pkey'))
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
