"""drop_unused_tasks_table

Revision ID: a3fd9f729cb9
Revises: 5bab562f2510
Create Date: 2026-06-28 08:17:54.426388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fd9f729cb9'
down_revision: Union[str, Sequence[str], None] = '5bab562f2510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('task_id', name=op.f('tasks_pkey'))
    )
    # ### end Alembic commands ###
